# Generated by Django 2.2.1 on 2019-08-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190826_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('search_radius', models.IntegerField()),
                ('star_standard', models.DecimalField(decimal_places=1, max_digits='2')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
